name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WEATHER_API_KEY: ${{secrets.WEATHER}}

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name : install
      run: |
        npm install
        
    - name: Build
      run: |
        npm run build

    - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
